export default {
    GET_LOGIN_API: "GET_LOGIN_API",
    GET_LOGIN_API_SUCCESS: "GET_LOGIN_API_SUCCESS",
    GET_LOGIN_API_FAIL: "GET_LOGIN_API_SUCCESS",

    GET_VENDOR_FROM_API : "GET_VENDOR_FROM_API" ,
    GET_VENDOR_SUCCESS: "GET_VENDOR_SUCCESS",

    GET_SITES_FROM_API : "GET_SITES_FROM_API",
    GET_SITES_FROM_API_SUCCESS : "GET_SITES_FROM_API_SUCCESS",

    GET_WEATHER_COUNTRY: "GET_WEATHER_COUNTRY",
    GET_WEATHER_COUNTRY_SUCCESS: "GET_WEATHER_COUNTRY_SUCESS",

    GLOBAL_HANDLE_SELECT_FILTER: "GLOBAL_HANDLE_SELECT_FILTER", 


}