export default {
    GET_LOGIN_API: "GET_LOGIN_API",
    GET_LOGOUT: "GET_LOGOUT",
    GET_LOGIN_API_SUCCESS: "GET_LOGIN_API_SUCCESS",
    GET_LOGIN_API_FAIL: "GET_LOGIN_API_FAIL",

    GET_VENDOR_FROM_API : "GET_VENDOR_FROM_API" ,
    GET_VENDOR_SUCCESS: "GET_VENDOR_SUCCESS",

    GET_SITES_FROM_API : "GET_SITES_FROM_API",
    GET_SITES_FROM_API_SUCCESS : "GET_SITES_FROM_API_SUCCESS",

    GET_WEATHER_COUNTRY: "GET_WEATHER_COUNTRY",
    GET_WEATHER_COUNTRY_SUCCESS: "GET_WEATHER_COUNTRY_SUCESS",

    // @LUCY
    GET_VENDOR_INVERTER_SITES:"GET_VENDOR_INVERTER_SITES",
    GET_VENDOR_INVERTER_SITES_SUCCESS:"GET_VENDOR_INVERTER_SITES_SUCCESS",

    GET_GLOBAL_HOME_STATUS_DATA:"GET_GLOBAL_HOME_STATUS_DATA",
    GET_GLOBAL_HOME_STATUS_DATA_SUCCESS:"GET_GLOBAL_HOME_STATUS_DATA_SUCCESS",

    GET_SITE_PROFILE_DATA:"GET_SITE_PROFILE_DATA",
    GET_SITE_PROFILE_DATA_SUCCESS:"GET_SITE_PROFILE_DATA_SUCCESS",

    GET_SITE_REPORT_DATA:"GET_SITE_REPORT_DATA",
    GET_SITE_REPORT_DATA_SUCCESS:"GET_SITE_REPORT_DATA_SUCCESS",

    GLOBAL_HANDLE_SELECT_FILTER: "GLOBAL_HANDLE_SELECT_FILTER", 
    

    // @mmh
    GET_VENDOR_SITE_DATA: "GET_VENDOR_SITE_DATA",
    GET_VENDOR_SITE_DATA_SUCCESS: "GET_VENDOR_SITE_DATA_SUCCESS",

}